language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install --upgrade pip
  - pip install -r requirements/dev.txt
script:
  - python setup.py lint
  - python setup.py coverage
  - python setup.py doctest
